// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Certificate - New Certificate object
type Certificate struct {
	// Optionally, drag/drop or upload all CA certificate(s) in PEM/Base64 format. Or paste certs' contents here. Certs can be used for client and/or server auth.
	Ca *string `json:"ca,omitempty"`
	// Drag/drop or upload host certificate, in PEM/Base64 format. Or paste its contents here.
	Cert string `json:"cert"`
	// Brief description of this certificate. Optional.
	Description *string `json:"description,omitempty"`
	// Name of the certificate.
	ID string `json:"id"`
	// List of configurations referencing this certificate.
	InUse []string `json:"inUse,omitempty"`
	// Passphrase. Optional.
	Passphrase *string `json:"passphrase,omitempty"`
	// Certificate private key.
	PrivKey string `json:"privKey"`
}
