// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ConfigGroups - a list of ConfigGroup objects
type ConfigGroups struct {
	// number of items present in the items array
	Count *int64        `json:"count,omitempty"`
	Items []ConfigGroup `json:"items,omitempty"`
}
