// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type ContainerType string

const (
	ContainerTypeDocker     ContainerType = "docker"
	ContainerTypeContainerd ContainerType = "containerd"
)

func (e ContainerType) ToPointer() *ContainerType {
	return &e
}

func (e *ContainerType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "docker":
		fallthrough
	case "containerd":
		*e = ContainerType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContainerType: %v", v)
	}
}

type Container struct {
	Containerd *ContainerdInfo `json:"containerd,omitempty"`
	Created    int64           `json:"created"`
	Docker     *DockerInfo     `json:"docker,omitempty"`
	ID         string          `json:"id"`
	Image      string          `json:"image"`
	Ips        []string        `json:"ips,omitempty"`
	Name       string          `json:"name"`
	Ports      []ContainerPort `json:"ports,omitempty"`
	Status     string          `json:"status"`
	Type       ContainerType   `json:"type"`
}
