// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DailyUsageMetrics struct {
	EndTime                int64 `json:"endTime"`
	ExemptedLicenseInBytes int64 `json:"exemptedLicenseInBytes"`
	InBytes                int64 `json:"inBytes"`
	InEvents               int64 `json:"inEvents"`
	OutBytes               int64 `json:"outBytes"`
	OutEvents              int64 `json:"outEvents"`
	StartTime              int64 `json:"startTime"`
}
