// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DistributedSummaries - a list of DistributedSummary objects
type DistributedSummaries struct {
	// number of items present in the items array
	Count *int64               `json:"count,omitempty"`
	Items []DistributedSummary `json:"items,omitempty"`
}
