// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EdgeFiles - a list of EdgeFile objects
type EdgeFiles struct {
	// number of items present in the items array
	Count *int64 `json:"count,omitempty"`
}
