// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// EventBreakerRulesets - a list of Event Breaker Ruleset objects
type EventBreakerRulesets struct {
	// number of items present in the items array
	Count *int64 `json:"count,omitempty"`
}
