// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ExistingDiag - a list of Diag objects
type ExistingDiag struct {
	// number of items present in the items array
	Count *int64 `json:"count,omitempty"`
	Items []Diag `json:"items,omitempty"`
}
