// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GrokFile - New GrokFile object
type GrokFile struct {
	Content string  `json:"content"`
	ID      string  `json:"id"`
	Size    int64   `json:"size"`
	Tags    *string `json:"tags,omitempty"`
}
