// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type InputCriblTCPConnections struct {
	// Select a Destination.
	Output string `json:"output"`
	// Select Pipeline or Pack. Optional.
	Pipeline *string `json:"pipeline,omitempty"`
}

type InputCriblTCPMetadata struct {
	// Field name
	Name string `json:"name"`
	// JavaScript expression to compute field's value, enclosed in quotes or backticks. (Can evaluate to a constant.)
	Value string `json:"value"`
}

// InputCriblTCPPqCompression - Codec to use to compress the persisted data.
type InputCriblTCPPqCompression string

const (
	InputCriblTCPPqCompressionNone InputCriblTCPPqCompression = "none"
	InputCriblTCPPqCompressionGzip InputCriblTCPPqCompression = "gzip"
)

func (e InputCriblTCPPqCompression) ToPointer() *InputCriblTCPPqCompression {
	return &e
}

func (e *InputCriblTCPPqCompression) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "none":
		fallthrough
	case "gzip":
		*e = InputCriblTCPPqCompression(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputCriblTCPPqCompression: %v", v)
	}
}

// InputCriblTCPPqMode - With Smart mode, PQ will write events to the filesystem only when it detects backpressure from the processing engine. With Always On mode, PQ will always write events directly to the queue before forwarding them to the processing engine.
type InputCriblTCPPqMode string

const (
	InputCriblTCPPqModeSmart  InputCriblTCPPqMode = "smart"
	InputCriblTCPPqModeAlways InputCriblTCPPqMode = "always"
)

func (e InputCriblTCPPqMode) ToPointer() *InputCriblTCPPqMode {
	return &e
}

func (e *InputCriblTCPPqMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "smart":
		fallthrough
	case "always":
		*e = InputCriblTCPPqMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputCriblTCPPqMode: %v", v)
	}
}

type InputCriblTCPPq struct {
	// The number of events to send downstream before committing that Stream has read them.
	CommitFrequency *int64 `json:"commitFrequency,omitempty"`
	// Codec to use to compress the persisted data.
	Compress *InputCriblTCPPqCompression `json:"compress,omitempty"`
	// The maximum number of events to hold in memory before writing the events to disk.
	MaxBufferSize *int64 `json:"maxBufferSize,omitempty"`
	// The maximum size to store in each queue file before closing and optionally compressing (KB, MB, etc.).
	MaxFileSize *string `json:"maxFileSize,omitempty"`
	// The maximum amount of disk space the queue is allowed to consume. Once reached, the system stops queueing and applies the fallback Queue-full behavior. Enter a numeral with units of KB, MB, etc.
	MaxSize *string `json:"maxSize,omitempty"`
	// With Smart mode, PQ will write events to the filesystem only when it detects backpressure from the processing engine. With Always On mode, PQ will always write events directly to the queue before forwarding them to the processing engine.
	Mode *InputCriblTCPPqMode `json:"mode,omitempty"`
	// The location for the persistent queue files. To this field's value, the system will append: /<worker-id>/inputs/<input-id>.
	Path *string `json:"path,omitempty"`
}

// InputCriblTCPTLSSettingsServerSideMaximumTLSVersion - Maximum TLS version to accept from connections.
type InputCriblTCPTLSSettingsServerSideMaximumTLSVersion string

const (
	InputCriblTCPTLSSettingsServerSideMaximumTLSVersionTlSv1  InputCriblTCPTLSSettingsServerSideMaximumTLSVersion = "TLSv1"
	InputCriblTCPTLSSettingsServerSideMaximumTLSVersionTlSv11 InputCriblTCPTLSSettingsServerSideMaximumTLSVersion = "TLSv1.1"
	InputCriblTCPTLSSettingsServerSideMaximumTLSVersionTlSv12 InputCriblTCPTLSSettingsServerSideMaximumTLSVersion = "TLSv1.2"
	InputCriblTCPTLSSettingsServerSideMaximumTLSVersionTlSv13 InputCriblTCPTLSSettingsServerSideMaximumTLSVersion = "TLSv1.3"
)

func (e InputCriblTCPTLSSettingsServerSideMaximumTLSVersion) ToPointer() *InputCriblTCPTLSSettingsServerSideMaximumTLSVersion {
	return &e
}

func (e *InputCriblTCPTLSSettingsServerSideMaximumTLSVersion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TLSv1":
		fallthrough
	case "TLSv1.1":
		fallthrough
	case "TLSv1.2":
		fallthrough
	case "TLSv1.3":
		*e = InputCriblTCPTLSSettingsServerSideMaximumTLSVersion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputCriblTCPTLSSettingsServerSideMaximumTLSVersion: %v", v)
	}
}

// InputCriblTCPTLSSettingsServerSideMinimumTLSVersion - Minimum TLS version to accept from connections.
type InputCriblTCPTLSSettingsServerSideMinimumTLSVersion string

const (
	InputCriblTCPTLSSettingsServerSideMinimumTLSVersionTlSv1  InputCriblTCPTLSSettingsServerSideMinimumTLSVersion = "TLSv1"
	InputCriblTCPTLSSettingsServerSideMinimumTLSVersionTlSv11 InputCriblTCPTLSSettingsServerSideMinimumTLSVersion = "TLSv1.1"
	InputCriblTCPTLSSettingsServerSideMinimumTLSVersionTlSv12 InputCriblTCPTLSSettingsServerSideMinimumTLSVersion = "TLSv1.2"
	InputCriblTCPTLSSettingsServerSideMinimumTLSVersionTlSv13 InputCriblTCPTLSSettingsServerSideMinimumTLSVersion = "TLSv1.3"
)

func (e InputCriblTCPTLSSettingsServerSideMinimumTLSVersion) ToPointer() *InputCriblTCPTLSSettingsServerSideMinimumTLSVersion {
	return &e
}

func (e *InputCriblTCPTLSSettingsServerSideMinimumTLSVersion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TLSv1":
		fallthrough
	case "TLSv1.1":
		fallthrough
	case "TLSv1.2":
		fallthrough
	case "TLSv1.3":
		*e = InputCriblTCPTLSSettingsServerSideMinimumTLSVersion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputCriblTCPTLSSettingsServerSideMinimumTLSVersion: %v", v)
	}
}

type InputCriblTCPTLSSettingsServerSide struct {
	// Path on server containing CA certificates to use. PEM format. Can reference $ENV_VARS.
	CaPath *string `json:"caPath,omitempty"`
	// Path on server containing certificates to use. PEM format. Can reference $ENV_VARS.
	CertPath *string `json:"certPath,omitempty"`
	// The name of the predefined certificate.
	CertificateName *string     `json:"certificateName,omitempty"`
	CommonNameRegex interface{} `json:"commonNameRegex,omitempty"`
	Disabled        *bool       `json:"disabled,omitempty"`
	// Maximum TLS version to accept from connections.
	MaxVersion *InputCriblTCPTLSSettingsServerSideMaximumTLSVersion `json:"maxVersion,omitempty"`
	// Minimum TLS version to accept from connections.
	MinVersion *InputCriblTCPTLSSettingsServerSideMinimumTLSVersion `json:"minVersion,omitempty"`
	// Passphrase to use to decrypt private key.
	Passphrase *string `json:"passphrase,omitempty"`
	// Path on server containing the private key to use. PEM format. Can reference $ENV_VARS.
	PrivKeyPath        *string     `json:"privKeyPath,omitempty"`
	RejectUnauthorized interface{} `json:"rejectUnauthorized,omitempty"`
	// Whether to require clients to present their certificates. Used to perform client authentication using SSL certs.
	RequestCert *bool `json:"requestCert,omitempty"`
}

type InputCriblTCPType string

const (
	InputCriblTCPTypeCriblTCP InputCriblTCPType = "cribl_tcp"
)

func (e InputCriblTCPType) ToPointer() *InputCriblTCPType {
	return &e
}

func (e *InputCriblTCPType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "cribl_tcp":
		*e = InputCriblTCPType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputCriblTCPType: %v", v)
	}
}

type InputCriblTCP struct {
	// Direct connections to Destinations, optionally via a Pipeline or a Pack.
	Connections []InputCriblTCPConnections `json:"connections,omitempty"`
	// Enable/disable this input
	Disabled *bool `json:"disabled,omitempty"`
	// Enable if the connection is proxied by a device that supports Proxy Protocol V1 or V2.
	EnableProxyHeader *bool `json:"enableProxyHeader,omitempty"`
	// Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere.
	Environment *string `json:"environment,omitempty"`
	// Address to bind on. Defaults to 0.0.0.0 (all addresses).
	Host string `json:"host"`
	// Unique ID for this input
	ID *string `json:"id,omitempty"`
	// Maximum number of active connections allowed per Worker Process, use 0 for unlimited
	MaxActiveCxn *int64 `json:"maxActiveCxn,omitempty"`
	// Fields to add to events from this input.
	Metadata []InputCriblTCPMetadata `json:"metadata,omitempty"`
	// Pipeline to process data from this Source before sending it through the Routes.
	Pipeline *string `json:"pipeline,omitempty"`
	// Port to listen on.
	Port int64            `json:"port"`
	Pq   *InputCriblTCPPq `json:"pq,omitempty"`
	// For details on Persistent Queues, see: [https://docs.cribl.io/stream/persistent-queues](https://docs.cribl.io/stream/persistent-queues)
	PqEnabled *bool `json:"pqEnabled,omitempty"`
	// Select whether to send data to Routes, or directly to Destinations.
	SendToRoutes *bool `json:"sendToRoutes,omitempty"`
	// Add tags for filtering and grouping in @{product}.
	Streamtags []string                            `json:"streamtags,omitempty"`
	TLS        *InputCriblTCPTLSSettingsServerSide `json:"tls,omitempty"`
	Type       *InputCriblTCPType                  `json:"type,omitempty"`
}
