// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type InputDatadogAgentConnections struct {
	// Select a Destination.
	Output string `json:"output"`
	// Select Pipeline or Pack. Optional.
	Pipeline *string `json:"pipeline,omitempty"`
}

type InputDatadogAgentMetadata struct {
	// Field name
	Name string `json:"name"`
	// JavaScript expression to compute field's value, enclosed in quotes or backticks. (Can evaluate to a constant.)
	Value string `json:"value"`
}

// InputDatadogAgentPqCompression - Codec to use to compress the persisted data.
type InputDatadogAgentPqCompression string

const (
	InputDatadogAgentPqCompressionNone InputDatadogAgentPqCompression = "none"
	InputDatadogAgentPqCompressionGzip InputDatadogAgentPqCompression = "gzip"
)

func (e InputDatadogAgentPqCompression) ToPointer() *InputDatadogAgentPqCompression {
	return &e
}

func (e *InputDatadogAgentPqCompression) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "none":
		fallthrough
	case "gzip":
		*e = InputDatadogAgentPqCompression(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputDatadogAgentPqCompression: %v", v)
	}
}

// InputDatadogAgentPqMode - With Smart mode, PQ will write events to the filesystem only when it detects backpressure from the processing engine. With Always On mode, PQ will always write events directly to the queue before forwarding them to the processing engine.
type InputDatadogAgentPqMode string

const (
	InputDatadogAgentPqModeSmart  InputDatadogAgentPqMode = "smart"
	InputDatadogAgentPqModeAlways InputDatadogAgentPqMode = "always"
)

func (e InputDatadogAgentPqMode) ToPointer() *InputDatadogAgentPqMode {
	return &e
}

func (e *InputDatadogAgentPqMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "smart":
		fallthrough
	case "always":
		*e = InputDatadogAgentPqMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputDatadogAgentPqMode: %v", v)
	}
}

type InputDatadogAgentPq struct {
	// The number of events to send downstream before committing that Stream has read them.
	CommitFrequency *int64 `json:"commitFrequency,omitempty"`
	// Codec to use to compress the persisted data.
	Compress *InputDatadogAgentPqCompression `json:"compress,omitempty"`
	// The maximum number of events to hold in memory before writing the events to disk.
	MaxBufferSize *int64 `json:"maxBufferSize,omitempty"`
	// The maximum size to store in each queue file before closing and optionally compressing (KB, MB, etc.).
	MaxFileSize *string `json:"maxFileSize,omitempty"`
	// The maximum amount of disk space the queue is allowed to consume. Once reached, the system stops queueing and applies the fallback Queue-full behavior. Enter a numeral with units of KB, MB, etc.
	MaxSize *string `json:"maxSize,omitempty"`
	// With Smart mode, PQ will write events to the filesystem only when it detects backpressure from the processing engine. With Always On mode, PQ will always write events directly to the queue before forwarding them to the processing engine.
	Mode *InputDatadogAgentPqMode `json:"mode,omitempty"`
	// The location for the persistent queue files. To this field's value, the system will append: /<worker-id>/inputs/<input-id>.
	Path *string `json:"path,omitempty"`
}

type InputDatadogAgentProxyMode struct {
	// Toggle to Yes to send key validation requests from Datadog Agent to the Datadog API. If toggled to No (the default), Stream handles key validation requests by always responding that the key is valid.
	Enabled bool `json:"enabled"`
}

// InputDatadogAgentTLSSettingsServerSideMaximumTLSVersion - Maximum TLS version to accept from connections.
type InputDatadogAgentTLSSettingsServerSideMaximumTLSVersion string

const (
	InputDatadogAgentTLSSettingsServerSideMaximumTLSVersionTlSv1  InputDatadogAgentTLSSettingsServerSideMaximumTLSVersion = "TLSv1"
	InputDatadogAgentTLSSettingsServerSideMaximumTLSVersionTlSv11 InputDatadogAgentTLSSettingsServerSideMaximumTLSVersion = "TLSv1.1"
	InputDatadogAgentTLSSettingsServerSideMaximumTLSVersionTlSv12 InputDatadogAgentTLSSettingsServerSideMaximumTLSVersion = "TLSv1.2"
	InputDatadogAgentTLSSettingsServerSideMaximumTLSVersionTlSv13 InputDatadogAgentTLSSettingsServerSideMaximumTLSVersion = "TLSv1.3"
)

func (e InputDatadogAgentTLSSettingsServerSideMaximumTLSVersion) ToPointer() *InputDatadogAgentTLSSettingsServerSideMaximumTLSVersion {
	return &e
}

func (e *InputDatadogAgentTLSSettingsServerSideMaximumTLSVersion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TLSv1":
		fallthrough
	case "TLSv1.1":
		fallthrough
	case "TLSv1.2":
		fallthrough
	case "TLSv1.3":
		*e = InputDatadogAgentTLSSettingsServerSideMaximumTLSVersion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputDatadogAgentTLSSettingsServerSideMaximumTLSVersion: %v", v)
	}
}

// InputDatadogAgentTLSSettingsServerSideMinimumTLSVersion - Minimum TLS version to accept from connections.
type InputDatadogAgentTLSSettingsServerSideMinimumTLSVersion string

const (
	InputDatadogAgentTLSSettingsServerSideMinimumTLSVersionTlSv1  InputDatadogAgentTLSSettingsServerSideMinimumTLSVersion = "TLSv1"
	InputDatadogAgentTLSSettingsServerSideMinimumTLSVersionTlSv11 InputDatadogAgentTLSSettingsServerSideMinimumTLSVersion = "TLSv1.1"
	InputDatadogAgentTLSSettingsServerSideMinimumTLSVersionTlSv12 InputDatadogAgentTLSSettingsServerSideMinimumTLSVersion = "TLSv1.2"
	InputDatadogAgentTLSSettingsServerSideMinimumTLSVersionTlSv13 InputDatadogAgentTLSSettingsServerSideMinimumTLSVersion = "TLSv1.3"
)

func (e InputDatadogAgentTLSSettingsServerSideMinimumTLSVersion) ToPointer() *InputDatadogAgentTLSSettingsServerSideMinimumTLSVersion {
	return &e
}

func (e *InputDatadogAgentTLSSettingsServerSideMinimumTLSVersion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "TLSv1":
		fallthrough
	case "TLSv1.1":
		fallthrough
	case "TLSv1.2":
		fallthrough
	case "TLSv1.3":
		*e = InputDatadogAgentTLSSettingsServerSideMinimumTLSVersion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputDatadogAgentTLSSettingsServerSideMinimumTLSVersion: %v", v)
	}
}

type InputDatadogAgentTLSSettingsServerSide struct {
	// Path on server containing CA certificates to use. PEM format. Can reference $ENV_VARS.
	CaPath *string `json:"caPath,omitempty"`
	// Path on server containing certificates to use. PEM format. Can reference $ENV_VARS.
	CertPath *string `json:"certPath,omitempty"`
	// The name of the predefined certificate.
	CertificateName *string     `json:"certificateName,omitempty"`
	CommonNameRegex interface{} `json:"commonNameRegex,omitempty"`
	Disabled        *bool       `json:"disabled,omitempty"`
	// Maximum TLS version to accept from connections.
	MaxVersion *InputDatadogAgentTLSSettingsServerSideMaximumTLSVersion `json:"maxVersion,omitempty"`
	// Minimum TLS version to accept from connections.
	MinVersion *InputDatadogAgentTLSSettingsServerSideMinimumTLSVersion `json:"minVersion,omitempty"`
	// Passphrase to use to decrypt private key.
	Passphrase *string `json:"passphrase,omitempty"`
	// Path on server containing the private key to use. PEM format. Can reference $ENV_VARS.
	PrivKeyPath        *string     `json:"privKeyPath,omitempty"`
	RejectUnauthorized interface{} `json:"rejectUnauthorized,omitempty"`
	// Whether to require clients to present their certificates. Used to perform client authentication using SSL certs.
	RequestCert *bool `json:"requestCert,omitempty"`
}

type InputDatadogAgentType string

const (
	InputDatadogAgentTypeDatadogAgent InputDatadogAgentType = "datadog_agent"
)

func (e InputDatadogAgentType) ToPointer() *InputDatadogAgentType {
	return &e
}

func (e *InputDatadogAgentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "datadog_agent":
		*e = InputDatadogAgentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for InputDatadogAgentType: %v", v)
	}
}

type InputDatadogAgent struct {
	// How often request activity is logged at the `info` level. A value of 1 would log every request, 10 every 10th request, etc.
	ActivityLogSampleRate *int64 `json:"activityLogSampleRate,omitempty"`
	// Toggle this to Yes to add request headers to events, in the __headers field.
	CaptureHeaders *bool `json:"captureHeaders,omitempty"`
	// Direct connections to Destinations, optionally via a Pipeline or a Pack.
	Connections []InputDatadogAgentConnections `json:"connections,omitempty"`
	// Enable/disable this input
	Disabled *bool `json:"disabled,omitempty"`
	// Enable if the connection is proxied by a device that supports Proxy Protocol V1 or V2.
	EnableProxyHeader *bool `json:"enableProxyHeader,omitempty"`
	// Optionally, enable this config only on a specified Git branch. If empty, will be enabled everywhere.
	Environment *string `json:"environment,omitempty"`
	// Toggle to Yes to extract each incoming metric to multiple events, one per data point. This works well when sending metrics to a statsd-type output. If sending metrics to DatadogHQ or any destination that accepts arbitrary JSON, leave toggled to No (the default).
	ExtractMetrics *bool `json:"extractMetrics,omitempty"`
	// Address to bind on. Defaults to 0.0.0.0 (all addresses).
	Host string `json:"host"`
	// Unique ID for this input
	ID *string `json:"id,omitempty"`
	// After the last response is sent, @{product} will wait this long for additional data before closing the socket connection. Minimum 1 sec.; maximum 600 sec. (10 min.).
	KeepAliveTimeout *int64 `json:"keepAliveTimeout,omitempty"`
	// Maximum number of active requests per Worker Process. Use 0 for unlimited.
	MaxActiveReq *int64 `json:"maxActiveReq,omitempty"`
	// Fields to add to events from this input.
	Metadata []InputDatadogAgentMetadata `json:"metadata,omitempty"`
	// Pipeline to process data from this Source before sending it through the Routes.
	Pipeline *string `json:"pipeline,omitempty"`
	// Port to listen on.
	Port int64                `json:"port"`
	Pq   *InputDatadogAgentPq `json:"pq,omitempty"`
	// For details on Persistent Queues, see: [https://docs.cribl.io/stream/persistent-queues](https://docs.cribl.io/stream/persistent-queues)
	PqEnabled *bool                       `json:"pqEnabled,omitempty"`
	ProxyMode *InputDatadogAgentProxyMode `json:"proxyMode,omitempty"`
	// How long to wait for an incoming request to complete before aborting it. Use 0 to disable.
	RequestTimeout *int64 `json:"requestTimeout,omitempty"`
	// Select whether to send data to Routes, or directly to Destinations.
	SendToRoutes *bool `json:"sendToRoutes,omitempty"`
	// How long @{product} should wait before assuming that an inactive socket has timed out. To wait forever, set to 0.
	SocketTimeout *int64 `json:"socketTimeout,omitempty"`
	// Add tags for filtering and grouping in @{product}.
	Streamtags []string                                `json:"streamtags,omitempty"`
	TLS        *InputDatadogAgentTLSSettingsServerSide `json:"tls,omitempty"`
	Type       *InputDatadogAgentType                  `json:"type,omitempty"`
}
