// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type JobStatus struct {
	Reason map[string]interface{} `json:"reason,omitempty"`
	State  State                  `json:"state"`
}
