// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Licenses - a list of License objects
type Licenses struct {
	// number of items present in the items array
	Count *int64    `json:"count,omitempty"`
	Items []License `json:"items,omitempty"`
}
