// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// LogFileContents - a list of any objects
type LogFileContents struct {
	// number of items present in the items array
	Count *int64                   `json:"count,omitempty"`
	Items []map[string]interface{} `json:"items,omitempty"`
}
