// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// NotificationTargets - a list of NotificationTarget objects
type NotificationTargets struct {
	// number of items present in the items array
	Count *int64               `json:"count,omitempty"`
	Items []NotificationTarget `json:"items,omitempty"`
}
