// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PipelineFunctionConfFunctionSpecificConfigs struct {
}

type PipelineFunctionConf struct {
	Conf PipelineFunctionConfFunctionSpecificConfigs `json:"conf"`
	// Simple description of this step
	Description *string `json:"description,omitempty"`
	// If true, data will not be pushed through this function
	Disabled *bool `json:"disabled,omitempty"`
	// Filter that selects data to be fed through this function
	Filter *string `json:"filter,omitempty"`
	// If true, stops the results of this function from being passed to the downstream functions
	Final *bool `json:"final,omitempty"`
	// Group ID
	GroupID *string `json:"groupId,omitempty"`
	// Function ID
	ID string `json:"id"`
}
