// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PolicyRules - a list of PolicyRule objects
type PolicyRules struct {
	// number of items present in the items array
	Count *int64       `json:"count,omitempty"`
	Items []PolicyRule `json:"items,omitempty"`
}
