// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PreviewRequestBody - PreviewRequestBody object
type PreviewRequestBody struct {
	Events  []interface{}   `json:"events"`
	Options *PreviewOptions `json:"options,omitempty"`
	Query   string          `json:"query"`
}
