// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PreviewResponseBody struct {
	Count                     int64         `json:"count"`
	Events                    []interface{} `json:"events"`
	ProcessingTimeMS          int64         `json:"processingTimeMS"`
	UseFormattedVisualization bool          `json:"useFormattedVisualization"`
}
