// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Processes - a list of Process objects
type Processes struct {
	// number of items present in the items array
	Count *int64 `json:"count,omitempty"`
}
