// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PushConfig - a list of any objects
type PushConfig struct {
	// number of items present in the items array
	Count *int64                   `json:"count,omitempty"`
	Items []map[string]interface{} `json:"items,omitempty"`
}
