// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RegexLibEntry - New RegexLibEntry object
type RegexLibEntry struct {
	// Brief description of this regex. Optional.
	Description *string `json:"description,omitempty"`
	ID          string  `json:"id"`
	Lib         *string `json:"lib,omitempty"`
	// Regex pattern. Required.
	Regex string `json:"regex"`
	// Sample data for this regex. Optional.
	SampleData *string `json:"sampleData,omitempty"`
	// One or more tags related to this regex. Optional.
	Tags *string `json:"tags,omitempty"`
}
