// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RestSecrets - a list of RestSecret objects
type RestSecrets struct {
	// number of items present in the items array
	Count *int64       `json:"count,omitempty"`
	Items []RestSecret `json:"items,omitempty"`
}
