// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SavedQueries - a list of SavedQuery objects
type SavedQueries struct {
	// number of items present in the items array
	Count *int64       `json:"count,omitempty"`
	Items []SavedQuery `json:"items,omitempty"`
}
