// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ScriptLibEntries - a list of Script objects
type ScriptLibEntries struct {
	// number of items present in the items array
	Count *int64           `json:"count,omitempty"`
	Items []ScriptLibEntry `json:"items,omitempty"`
}
