// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SearchParameter struct {
	DefaultValue interface{}         `json:"defaultValue,omitempty"`
	Name         string              `json:"name"`
	Type         SearchParameterType `json:"type"`
}
