// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SearchTerm struct {
	IsCaseSensitive bool   `json:"isCaseSensitive"`
	Term            string `json:"term"`
}
