// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SearchJobErrorStateConfig struct {
	Coordinated   bool     `json:"coordinated"`
	ErrorMessages []string `json:"errorMessages"`
}
