// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SystemInfoObjects - a list of SystemInfo objects
type SystemInfoObjects struct {
	// number of items present in the items array
	Count *int64       `json:"count,omitempty"`
	Items []SystemInfo `json:"items,omitempty"`
}
