// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SystemInfoConf struct {
	ConfVersion *string `json:"confVersion,omitempty"`
	Inputs      int64   `json:"inputs"`
	Outputs     int64   `json:"outputs"`
	Pipelines   int64   `json:"pipelines"`
	Routes      int64   `json:"routes"`
	Rules       int64   `json:"rules"`
}

type SystemInfoCpus struct {
	Model string                 `json:"model"`
	Speed int64                  `json:"speed"`
	Times map[string]interface{} `json:"times"`
}

type SystemInfoDiskUsage struct {
	BytesAvailable int64  `json:"bytesAvailable"`
	BytesUsed      int64  `json:"bytesUsed"`
	DiskPath       string `json:"diskPath"`
	TotalDiskSize  int64  `json:"totalDiskSize"`
}

type SystemInfoEnv struct {
}

type SystemInfoLimitsSamples struct {
	MaxSize string `json:"maxSize"`
}

type SystemInfoLimits struct {
	Samples SystemInfoLimitsSamples `json:"samples"`
}

type SystemInfoMemory struct {
	Free  int64 `json:"free"`
	Total int64 `json:"total"`
}

type SystemInfoOs struct {
	Arch       string `json:"arch"`
	Endianness string `json:"endianness"`
	Platform   string `json:"platform"`
	Release    string `json:"release"`
	Type       string `json:"type"`
}

type SystemInfo struct {
	Build           map[string]interface{} `json:"BUILD"`
	APIPort         int64                  `json:"apiPort"`
	Conf            SystemInfoConf         `json:"conf"`
	ConfigPath      string                 `json:"configPath"`
	Cpus            []SystemInfoCpus       `json:"cpus"`
	DiskUsage       SystemInfoDiskUsage    `json:"diskUsage"`
	DistMode        AppMode                `json:"distMode"`
	Env             SystemInfoEnv          `json:"env"`
	GUID            string                 `json:"guid"`
	Hostname        string                 `json:"hostname"`
	InstallPath     string                 `json:"installPath"`
	License         LicenseInfo            `json:"license"`
	Limits          SystemInfoLimits       `json:"limits"`
	Loadavg         []int64                `json:"loadavg"`
	Memory          SystemInfoMemory       `json:"memory"`
	Messages        []BulletinMessage      `json:"messages"`
	Net             map[string]interface{} `json:"net"`
	Os              SystemInfoOs           `json:"os"`
	SystemConf      SystemConf             `json:"systemConf"`
	Uptime          int64                  `json:"uptime"`
	Version         string                 `json:"version"`
	WorkerProcesses int64                  `json:"workerProcesses"`
}
