// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// User - New User object
type User struct {
	CurrentPassword *string  `json:"currentPassword,omitempty"`
	Disabled        bool     `json:"disabled"`
	Email           string   `json:"email"`
	First           string   `json:"first"`
	ID              string   `json:"id"`
	Last            string   `json:"last"`
	Password        *string  `json:"password,omitempty"`
	Roles           []string `json:"roles,omitempty"`
	Username        string   `json:"username"`
}
