// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"Cribl/internal/sdk"
	"Cribl/internal/sdk/pkg/models/operations"
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &CertificateDataSource{}
var _ datasource.DataSourceWithConfigure = &CertificateDataSource{}

func NewCertificateDataSource() datasource.DataSource {
	return &CertificateDataSource{}
}

// CertificateDataSource is the data source implementation.
type CertificateDataSource struct {
	client *sdk.CriblTerraform
}

// CertificateDataSourceModel describes the data model.
type CertificateDataSourceModel struct {
	Ca          types.String   `tfsdk:"ca"`
	Cert        types.String   `tfsdk:"cert"`
	Description types.String   `tfsdk:"description"`
	ID          types.String   `tfsdk:"id"`
	InUse       []types.String `tfsdk:"in_use"`
	Passphrase  types.String   `tfsdk:"passphrase"`
	PrivKey     types.String   `tfsdk:"priv_key"`
}

// Metadata returns the data source type name.
func (r *CertificateDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_certificate"
}

// Schema defines the schema for the data source.
func (r *CertificateDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Certificate DataSource",

		Attributes: map[string]schema.Attribute{
			"ca": schema.StringAttribute{
				Computed:    true,
				Description: `Optionally, drag/drop or upload all CA certificate(s) in PEM/Base64 format. Or paste certs' contents here. Certs can be used for client and/or server auth.`,
			},
			"cert": schema.StringAttribute{
				Computed:    true,
				Description: `Drag/drop or upload host certificate, in PEM/Base64 format. Or paste its contents here.`,
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: `Brief description of this certificate. Optional.`,
			},
			"id": schema.StringAttribute{
				Required:    true,
				Description: `Unique ID`,
			},
			"in_use": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `List of configurations referencing this certificate.`,
			},
			"passphrase": schema.StringAttribute{
				Computed:    true,
				Description: `Passphrase. Optional.`,
			},
			"priv_key": schema.StringAttribute{
				Computed:    true,
				Description: `Certificate private key.`,
			},
		},
	}
}

func (r *CertificateDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.CriblTerraform)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.CriblTerraform, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *CertificateDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *CertificateDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	id := data.ID.ValueString()
	request := operations.GetCertificateRequest{
		ID: id,
	}
	res, err := r.client.Certificates.GetCertificate(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.Certificate == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromGetResponse(res.Certificate)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
