// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"Cribl/internal/sdk/pkg/models/shared"
)

func (r *PipelineDataSourceModel) RefreshFromGetResponse(resp *shared.Error) {

}
