// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateDatasetObjectResponse struct {
	ContentType string
	// a list of Dataset objects
	Dataset interface{}
	// Unauthorized
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
