// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateLookupResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of LookupFile objects
	LookupFiles *shared.LookupFiles
	StatusCode  int
	RawResponse *http.Response
}
