// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateCommitResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of GitCommitSummary objects
	GitCommit   *shared.GitCommit
	StatusCode  int
	RawResponse *http.Response
}
