// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type CreateOutputObjectResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of Output objects
	Outputs     *shared.Outputs
	StatusCode  int
	RawResponse *http.Response
}
