// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type DeleteOutputIDRequest struct {
	// Unique ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type DeleteOutputIDResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of Output objects
	Outputs     *shared.Outputs
	StatusCode  int
	RawResponse *http.Response
}
