// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetDiagBundleResponse struct {
	ContentType string
	// Unauthorized
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
	// A tar.gz file consisting all configuration files and recent logs
	GetDiagBundle200ApplicationTarPlusGzipBinaryString []byte
}
