// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetFeatureRequest struct {
	// Feature id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetFeatureResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of FeaturesEntry objects
	FeaturesEntry *shared.FeaturesEntry
	StatusCode    int
	RawResponse   *http.Response
}
