// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetGroupBundleRequest struct {
	// DeployRequest object
	DeployRequest *shared.DeployRequest `request:"mediaType=application/json"`
	// Group ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetGroupBundleResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of string objects
	GroupBundle *shared.GroupBundle
	StatusCode  int
	RawResponse *http.Response
}
