// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetLoggerConfigRequest struct {
	// Unique ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetLoggerConfigResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of LoggerConfig objects
	LoggerConfig *shared.LoggerConfig
	StatusCode   int
	RawResponse  *http.Response
}
