// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetRestSecretRequest struct {
	// Unique ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetRestSecretResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of RestSecret objects
	RestSecret  *shared.RestSecret
	StatusCode  int
	RawResponse *http.Response
}
