// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetRouteListIDRequest struct {
	// There is only one route entity and it should be accessed with id: default.
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetRouteListIDResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of Routes objects
	Routes      *shared.Routes
	StatusCode  int
	RawResponse *http.Response
}
