// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetSearchTimelineRequest struct {
	// search job id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetSearchTimelineResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// SearchTimeline object
	SearchTimeline *shared.SearchTimeline
	StatusCode     int
	RawResponse    *http.Response
}
