// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListAppscopeLibEntriesResponse struct {
	// a list of AppscopeLibEntry objects
	AppScopeLibEntries *shared.AppScopeLibEntries
	ContentType        string
	// Unexpected error
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
