// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListBytesRequest struct {
	// The number of bytes to return;   this value could be constrained by system limits.
	BytesRequested *int64 `queryParam:"style=form,explode=true,name=bytesRequested"`
	// The path to the file to sample
	Path string `queryParam:"style=form,explode=true,name=path"`
}

type ListBytesResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of SampleFile objects
	SampleFiles *shared.SampleFiles
	StatusCode  int
	RawResponse *http.Response
}
