// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListFeaturesResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of FeaturesEntry objects
	FeaturesEntries *shared.FeaturesEntries
	StatusCode      int
	RawResponse     *http.Response
}
