// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type ListAuthGroupResponse struct {
	ContentType string
	// a list of CrudEntityBase objects
	CrudEntityBases *shared.CrudEntityBases
	// Unauthorized
	Error       *shared.Error
	StatusCode  int
	RawResponse *http.Response
}
