// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type PostEventBreakerResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of Event Breaker Ruleset objects
	EventBreakerRulesets *shared.EventBreakerRulesets
	StatusCode           int
	RawResponse          *http.Response
}
