// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type PushCurrentConfigResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of any objects
	PushConfig  *shared.PushConfig
	StatusCode  int
	RawResponse *http.Response
}
