// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type QueryMetricsRequest struct {
	// earliest time to query against
	Earliest *int64 `queryParam:"style=form,explode=true,name=earliest"`
	// a js expression to apply against the metrics returned (can filter dimensions)
	FilterExpr *string `queryParam:"style=form,explode=true,name=filterExpr"`
	// latest time to query against
	Latest *int64 `queryParam:"style=form,explode=true,name=latest"`
	// can be a regex or an array of metric names
	MetricNameFilter *string `queryParam:"style=form,explode=true,name=metricNameFilter"`
	// buckets in the past to include in the query results
	NumBuckets *int64 `queryParam:"style=form,explode=true,name=numBuckets"`
}

type QueryMetricsResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of MetricNameInfo objects
	MetricsInfo *shared.MetricsInfo
	StatusCode  int
	RawResponse *http.Response
}
