// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdatePipelineIDRequest struct {
	// Pipeline object to be updated
	Pipeline *shared.Pipeline `request:"mediaType=application/json"`
	// Unique ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type UpdatePipelineIDResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of Pipeline objects
	Pipelines   *shared.Pipelines
	StatusCode  int
	RawResponse *http.Response
}
