// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateSavedQueriesRequest struct {
	// SavedQuery object to be updated
	SavedQuery *shared.SavedQuery `request:"mediaType=application/json"`
	// Unique ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type UpdateSavedQueriesResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of SavedQuery objects
	SavedQuery  *shared.SavedQuery
	StatusCode  int
	RawResponse *http.Response
}
