// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateSavedJobRequest struct {
	// SavedJob object to be updated
	SavedJob *shared.SavedJob `request:"mediaType=application/json"`
	// Unique ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type UpdateSavedJobResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of SavedJob objects
	SavedJob    *shared.SavedJob
	StatusCode  int
	RawResponse *http.Response
}
