// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Cribl/internal/sdk/pkg/models/shared"
	"net/http"
)

type UpdateSchemaIDRequest struct {
	// Schema object to be updated
	SchemaLibEntry *shared.SchemaLibEntry `request:"mediaType=application/json"`
	// Unique ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type UpdateSchemaIDResponse struct {
	ContentType string
	// Unauthorized
	Error *shared.Error
	// a list of Schema objects
	SchemaLibEntries *shared.SchemaLibEntries
	StatusCode       int
	RawResponse      *http.Response
}
